#include "Type.h"

REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(void,		void);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(bool,		bool);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(int8_t,	int8);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(uint8_t,	uint8);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(int16_t,	int16);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(uint16_t,	uint16);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(int32_t,	int32);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(uint32_t,	uint32);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(int64_t,	int64);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(uint64_t,	uint64);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(float,		float);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(double,	double);
REFLECTION_PRIMITIVE_TYPE_IMPLEMENTATION(char,		char);
